# Generated by Django 4.0.1 on 2022-06-04 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsstory',
            options={'ordering': ('-pub_date',)},
        ),
    ]
